// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vulcan.Models;

namespace vulcan.Migrations
{
    [DbContext(typeof(vulcanContext))]
    [Migration("20190121171719_Scan")]
    partial class Scan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("vulcan.Models.Vulnerabilities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessComplexity");

                    b.Property<string>("Authentication");

                    b.Property<string>("AvaliabilityImpact");

                    b.Property<string>("ConfidentialityImpact");

                    b.Property<string>("Description");

                    b.Property<string>("GainedAccess");

                    b.Property<int>("Gravity");

                    b.Property<string>("IntegrityImpact");

                    b.Property<string>("Product");

                    b.Property<double>("Score");

                    b.Property<string>("Type");

                    b.Property<string>("Vendor");

                    b.Property<string>("Version");

                    b.Property<string>("VulnerabilitieID");

                    b.HasKey("ID");

                    b.ToTable("Vulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
